spring:
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/demoscdgcg/CentralCofigAllPropertiesFile.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true